# Generated by Django 5.2.1 on 2025-05-20 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_group_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Group',
            new_name='group',
        ),
    ]
